steps:
  - label: "New Beta Release"
    plugins:
      - automattic/a8c-ci-toolkit#3.0.1
    command: |
      .buildkite/commands/configure-environment.sh

      echo '--- :shipit: New beta release'
      bundle exec fastlane new_beta_release skip_confirm:true
